"""empty message

Revision ID: c127af30b387
Revises: f5b6ee30663e
Create Date: 2020-11-21 00:37:14.327388

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c127af30b387'
down_revision = 'f5b6ee30663e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_events_Email', table_name='events')
    op.drop_index('ix_events_Meet', table_name='events')
    op.drop_table('events')
    op.drop_index('ix_post_timestamp', table_name='post')
    op.drop_table('post')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('body', sa.VARCHAR(length=140), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_post_timestamp', 'post', ['timestamp'], unique=False)
    op.create_table('events',
    sa.Column('Id', sa.INTEGER(), nullable=False),
    sa.Column('Email', sa.VARCHAR(length=250), nullable=True),
    sa.Column('Title', sa.VARCHAR(length=250), nullable=True),
    sa.Column('EDate', sa.VARCHAR(length=120), nullable=True),
    sa.Column('Time', sa.VARCHAR(length=120), nullable=True),
    sa.Column('Meet', sa.VARCHAR(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_index('ix_events_Meet', 'events', ['Meet'], unique=1)
    op.create_index('ix_events_Email', 'events', ['Email'], unique=1)
    # ### end Alembic commands ###
