"""adding table

Revision ID: f5b6ee30663e
Revises: 31586e1ad4e9
Create Date: 2020-11-01 05:32:23.757750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5b6ee30663e'
down_revision = '31586e1ad4e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('Email', sa.String(length=250), nullable=True),
    sa.Column('Title', sa.String(length=250), nullable=True),
    sa.Column('EDate', sa.String(length=120), nullable=True),
    sa.Column('Time', sa.String(length=120), nullable=True),
    sa.Column('Meet', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_index(op.f('ix_events_Email'), 'events', ['Email'], unique=True)
    op.create_index(op.f('ix_events_Meet'), 'events', ['Meet'], unique=True)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=140), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_post_timestamp'), 'post', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_post_timestamp'), table_name='post')
    op.drop_table('post')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_events_Meet'), table_name='events')
    op.drop_index(op.f('ix_events_Email'), table_name='events')
    op.drop_table('events')
    # ### end Alembic commands ###
